require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enbled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**'